<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Version>4.9.0</Version>
    <Company>sgtlaggy</Company>
    <Copyright>Copyright © sgtlaggy 2026</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <DistDir>dist</DistDir>
    <DirToZip>$(DistDir)\zip</DirToZip>
    <ModDir>$(DirToZip)\SPT_Runtime\user\mods\$(MSBuildProjectName)</ModDir>
  </PropertyGroup>

  <Target Name="BuildDist" AfterTargets="AfterBuild">
    <ItemGroup>
      <OutputDLL Include="$(TargetPath)"/>
      <Resources Include="Resources\**\*.*"/>
    </ItemGroup>

    <RemoveDir Directories="$(DistDir)"/>
    <Copy
        SourceFiles="@(OutputDLL);@(Resources)"
        DestinationFolder="$(ModDir)\%(RecursiveDir)"/>
  </Target>
  <Target Name="CopyPDB" AfterTargets="BuildDist" Condition="'$(Configuration)' == 'Debug'">
    <Copy
        SourceFiles="$(TargetDir)$(TargetName).pdb"
        DestinationFolder="$(ModDir)"/>
  </Target>
  <Target Name="Zip" AfterTargets="BuildDist" Condition="'$(Configuration)' == 'Release'">
    <ZipDirectory
        SourceDirectory="$(DirToZip)"
        DestinationFile="$(DistDir)\$(MSBuildProjectName)-$(Version).zip"/>
  </Target>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Web" Version="4.1.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.0" />
  </ItemGroup>

</Project>
